[package]
name = "pdf_tools"
version = "0.1.0"
authors = ["Sebastian K <s3bk@protonmail.com>"]
edition = "2018"

[dependencies]
pdf = { git = "https://github.com/pdf-rs/pdf", branch="dev" }
pdf_encoding = "*"
byteorder = "*"
utf16-ext = "*"
log = "*"
